# Generated by Django 2.0.2 on 2018-04-02 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_categoria', models.IntegerField()),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_chamado', models.IntegerField()),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=255)),
                ('data_abertura', models.DateField(auto_now=True)),
                ('data_atendimento', models.DateField(blank=True)),
                ('id_categoria', models.ForeignKey(null=True, on_delete=True, related_name='chamado_categoria', to='fcsolutions.Categorias')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_departamento', models.IntegerField()),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_instituicao', models.IntegerField()),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pessoa', models.IntegerField()),
                ('nome', models.CharField(max_length=128)),
                ('cpf', models.CharField(max_length=11, verbose_name='cpf')),
                ('email', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=10)),
                ('idade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_status', models.IntegerField()),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fcsolutions.Pessoa')),
            ],
            bases=('fcsolutions.pessoa',),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='departamento',
            name='id_instituicao',
            field=models.ForeignKey(null=True, on_delete=True, related_name='Departamento_Instituiçao', to='fcsolutions.Instituicao'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='id_funcionario_solicitante',
            field=models.ForeignKey(null=True, on_delete=True, related_name='Funcionario_chamado', to='fcsolutions.Pessoa'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='id_funcionario_solucionou',
            field=models.ForeignKey(blank=True, null=True, on_delete=True, related_name='Funcionarioti_chamado', to='fcsolutions.Pessoa'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='id_status',
            field=models.ForeignKey(null=True, on_delete=True, related_name='chamado_status', to='fcsolutions.Status'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='id_Departamento',
            field=models.ForeignKey(null=True, on_delete=True, related_name='Funcionario_Departamento', to='fcsolutions.Pessoa'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='id_funcionario',
            field=models.ForeignKey(null=True, on_delete=True, related_name='Pessoa_Funcionario', to='fcsolutions.Pessoa'),
        ),
    ]
