# Generated by Django 2.0.2 on 2018-04-03 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcsolutions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='id_Departamento',
            new_name='id_departamento',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='idade',
        ),
    ]
